import type { Agent, Payment } from "@/lib/api/types";

export const demoAgents: Agent[] = [
  {
    id: "agt_72b9c1e2",
    name: "Procurement Scout",
    status: "active",
    base_currency: "USD",
    balance: "12480.00",
    spent_today: "820.40",
    remaining_today: "1179.60",
    rules: { max_per_transaction: "750.00", max_per_day: "2000.00", allowed_counterparty_ids: null },
    wewire_sub_customer_id: "ww_sub_9c81f2",
    key_prefix: "krx_live_7fb2",
    created_at: "2026-08-24T09:12:00Z",
  },
  {
    id: "agt_88f13ad7",
    name: "Research Runner",
    status: "active",
    base_currency: "USDC",
    balance: "7840.25",
    spent_today: "412.00",
    remaining_today: "588.00",
    rules: { max_per_transaction: "300.00", max_per_day: "1000.00", allowed_counterparty_ids: ["agt_72b9c1e2"] },
    wewire_sub_customer_id: "ww_sub_2f422e",
    key_prefix: "krx_live_a18e",
    created_at: "2026-08-25T13:44:00Z",
  },
  {
    id: "agt_31d908be",
    name: "Travel Pilot",
    status: "frozen",
    base_currency: "EUR",
    balance: "4530.80",
    spent_today: "1184.90",
    remaining_today: "315.10",
    rules: { max_per_transaction: "500.00", max_per_day: "1500.00", allowed_counterparty_ids: null },
    wewire_sub_customer_id: "ww_sub_d1007a",
    key_prefix: null,
    created_at: "2026-08-26T07:30:00Z",
  },
];

export const demoPayments: Payment[] = [
  {
    id: "pay_54d91d",
    agent_id: "agt_72b9c1e2",
    kind: "agent_transfer",
    status: "executed",
    amount: "89.00",
    currency: "USD",
    counterparty_agent_id: "agt_88f13ad7",
    counterparty_detail: null,
    rule_violated: null,
    failure_reason: null,
    wewire_transaction_id: "ww_tx_88ac1e",
    memo: "Product catalog enrichment",
    created_at: "2026-08-29T15:42:00Z",
  },
  {
    id: "pay_a100e3",
    agent_id: "agt_31d908be",
    kind: "vendor_payout",
    status: "blocked",
    amount: "960.00",
    currency: "EUR",
    counterparty_agent_id: null,
    counterparty_detail: { account_name: "Westline Travel", network: "ATM" },
    rule_violated: "max_per_transaction",
    failure_reason: null,
    wewire_transaction_id: null,
    memo: "Hotel reservation",
    created_at: "2026-08-29T15:38:00Z",
  },
  {
    id: "pay_2f662a",
    agent_id: "agt_88f13ad7",
    kind: "vendor_payout",
    status: "executed",
    amount: "120.00",
    currency: "USDC",
    counterparty_agent_id: null,
    counterparty_detail: { account_name: "Vector Dataset Co.", network: "ATM" },
    rule_violated: null,
    failure_reason: null,
    wewire_transaction_id: "ww_tx_19e003",
    memo: "Evaluation dataset license",
    created_at: "2026-08-29T15:31:00Z",
  },
  {
    id: "pay_7c146f",
    agent_id: "agt_72b9c1e2",
    kind: "mobile_money",
    status: "executed",
    amount: "240.00",
    currency: "GHS",
    counterparty_agent_id: null,
    counterparty_detail: { account_name: "Kojo Mensah", network: "MTN" },
    rule_violated: null,
    failure_reason: null,
    wewire_transaction_id: "ww_tx_4518c9",
    memo: "Local courier payout",
    created_at: "2026-08-29T15:14:00Z",
  },
];

export const agentNames = Object.fromEntries(demoAgents.map((agent) => [agent.id, agent.name]));
